<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>nhs-server</artifactId>
        <groupId>group.aitools.nhs</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>nhs-extend</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>nhs-monitor-admin</module>
        <module>nhs-snailai-server</module>
        <module>nhs-snailjob-server</module>
    </modules>

</project>
