package group.aitools.nhs.platform.data.web;

import com.fasterxml.jackson.annotation.JsonAnySetter;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;

/** Candidate SQL generated by a model or submitted by the authenticated user. */
public record DataQueryRequest(
    @NotNull @Positive Long datasetId,
    @Positive Long taskId,
    @Positive Long runId,
    @Positive Long conversationId,
    @NotBlank @Size(max = 4000) String userQuery,
    @NotBlank @Size(max = 65536) String sql
) {

    @JsonAnySetter
    public void rejectUnknownField(String field, Object ignored) {
        throw new IllegalArgumentException("不支持的数据查询字段：" + field);
    }
}
