package group.aitools.nhs.runtime.spi;

/**
 * 定义运行时事件相关的可选值。
 */
public enum RuntimeEventType {
    RUN_STARTED,
    RUN_FINISHED,
    MODEL_CALL_STARTED,
    MODEL_CALL_FINISHED,
    TEXT_STARTED,
    TEXT_DELTA,
    TEXT_FINISHED,
    THINKING_STARTED,
    THINKING_DELTA,
    THINKING_FINISHED,
    DATA_STARTED,
    DATA_DELTA,
    DATA_FINISHED,
    TOOL_CALL_STARTED,
    TOOL_CALL_DELTA,
    TOOL_CALL_FINISHED,
    TOOL_RESULT_STARTED,
    TOOL_RESULT_DELTA,
    TOOL_RESULT_FINISHED,
    APPROVAL_REQUIRED,
    APPROVAL_RESOLVED,
    EXTERNAL_EXECUTION_REQUIRED,
    EXTERNAL_EXECUTION_RESOLVED,
    SUBAGENT_EVENT,
    PERMISSION_DENIED,
    ITERATION_LIMIT_REACHED,
    RESULT,
    CANCELLED,
    CUSTOM,
    FAILED
}
