/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";
import ClientLayout from "@/layouts/client-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
  client: ClientLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "agent-center": () => import("@/views/agent-center/index.vue"),
  "agent-debug": () => import("@/views/agent-debug/index.vue"),
  automation: () => import("@/views/automation/index.vue"),
  chatbi: () => import("@/views/chatbi/index.vue"),
  client: () => import("@/views/client/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  "data-portal": () => import("@/views/data-portal/index.vue"),
  "data-source": () => import("@/views/data-source/index.vue"),
  "embed-chat": () => import("@/views/embed-chat/index.vue"),
  examples: () => import("@/views/examples/index.vue"),
  home: () => import("@/views/home/index.vue"),
  knowledge: () => import("@/views/knowledge/index.vue"),
  memory: () => import("@/views/memory/index.vue"),
  "open-api": () => import("@/views/open-api/index.vue"),
  "personal-center": () => import("@/views/personal-center/index.vue"),
  "project-center": () => import("@/views/project-center/index.vue"),
  "prompt-studio": () => import("@/views/prompt-studio/index.vue"),
  "resource-center": () => import("@/views/resource-center/index.vue"),
  "risk-control": () => import("@/views/risk-control/index.vue"),
  "saved-reports": () => import("@/views/saved-reports/index.vue"),
  "scenario-templates": () => import("@/views/scenario-templates/index.vue"),
  "slash-commands": () => import("@/views/slash-commands/index.vue"),
  system: () => import("@/views/system/index.vue"),
  "task-center": () => import("@/views/task-center/index.vue"),
  "token-stats": () => import("@/views/token-stats/index.vue"),
  "widget-debugger": () => import("@/views/widget-debugger/index.vue"),
  workspace: () => import("@/views/workspace/index.vue"),
};
