/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'agent-center',
    path: '/agent-center',
    component: 'layout.base$view.agent-center',
    meta: {
      title: 'agent-center',
      i18nKey: 'route.agent-center'
    }
  },
  {
    name: 'agent-debug',
    path: '/agent-debug',
    component: 'layout.base$view.agent-debug',
    meta: {
      title: 'agent-debug',
      i18nKey: 'route.agent-debug'
    }
  },
  {
    name: 'automation',
    path: '/automation',
    component: 'layout.base$view.automation',
    meta: {
      title: 'automation',
      i18nKey: 'route.automation'
    }
  },
  {
    name: 'chatbi',
    path: '/chatbi',
    component: 'layout.base$view.chatbi',
    meta: {
      title: 'chatbi',
      i18nKey: 'route.chatbi'
    }
  },
  {
    name: 'client',
    path: '/app',
    alias: '/client',
    component: 'layout.client$view.client',
    meta: {
      title: 'client',
      i18nKey: 'route.client',
      hideInMenu: true
    }
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard'
    }
  },
  {
    name: 'data-portal',
    path: '/data-portal',
    component: 'layout.base$view.data-portal',
    meta: {
      title: 'data-portal',
      i18nKey: 'route.data-portal'
    }
  },
  {
    name: 'data-source',
    path: '/data-source',
    component: 'layout.base$view.data-source',
    meta: {
      title: 'data-source',
      i18nKey: 'route.data-source'
    }
  },
  {
    name: 'embed-chat',
    path: '/embed/chat',
    component: 'layout.blank$view.embed-chat',
    meta: {
      title: 'embed-chat',
      i18nKey: 'route.embed-chat',
      constant: true
    }
  },
  {
    name: 'examples',
    path: '/examples',
    component: 'layout.base$view.examples',
    meta: {
      title: 'examples',
      i18nKey: 'route.examples'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'knowledge',
    path: '/knowledge',
    component: 'layout.base$view.knowledge',
    meta: {
      title: 'knowledge',
      i18nKey: 'route.knowledge'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'memory',
    path: '/memory',
    component: 'layout.base$view.memory',
    meta: {
      title: 'memory',
      i18nKey: 'route.memory'
    }
  },
  {
    name: 'open-api',
    path: '/open-api',
    component: 'layout.base$view.open-api',
    meta: {
      title: 'open-api',
      i18nKey: 'route.open-api'
    }
  },
  {
    name: 'personal-center',
    path: '/personal-center',
    component: 'layout.base$view.personal-center',
    meta: {
      title: 'personal-center',
      i18nKey: 'route.personal-center',
      hideInMenu: true
    }
  },
  {
    name: 'project-center',
    path: '/project-center',
    component: 'layout.base$view.project-center',
    meta: {
      title: 'project-center',
      i18nKey: 'route.project-center'
    }
  },
  {
    name: 'prompt-studio',
    path: '/prompt-studio',
    component: 'layout.base$view.prompt-studio',
    meta: {
      title: 'prompt-studio',
      i18nKey: 'route.prompt-studio'
    }
  },
  {
    name: 'resource-center',
    path: '/resource-center',
    component: 'layout.base$view.resource-center',
    meta: {
      title: 'resource-center',
      i18nKey: 'route.resource-center'
    }
  },
  {
    name: 'risk-control',
    path: '/risk-control',
    component: 'layout.base$view.risk-control',
    meta: {
      title: 'risk-control',
      i18nKey: 'route.risk-control'
    }
  },
  {
    name: 'saved-reports',
    path: '/saved-reports',
    component: 'layout.base$view.saved-reports',
    meta: {
      title: 'saved-reports',
      i18nKey: 'route.saved-reports'
    }
  },
  {
    name: 'scenario-templates',
    path: '/scenario-templates',
    component: 'layout.base$view.scenario-templates',
    meta: {
      title: 'scenario-templates',
      i18nKey: 'route.scenario-templates'
    }
  },
  {
    name: 'slash-commands',
    path: '/slash-commands',
    component: 'layout.base$view.slash-commands',
    meta: {
      title: 'slash-commands',
      i18nKey: 'route.slash-commands'
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base$view.system',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    }
  },
  {
    name: 'task-center',
    path: '/task-center',
    component: 'layout.base$view.task-center',
    meta: {
      title: 'task-center',
      i18nKey: 'route.task-center'
    }
  },
  {
    name: 'token-stats',
    path: '/token-stats',
    component: 'layout.base$view.token-stats',
    meta: {
      title: 'token-stats',
      i18nKey: 'route.token-stats'
    }
  },
  {
    name: 'widget-debugger',
    path: '/client/debug',
    component: 'layout.base$view.widget-debugger',
    meta: {
      title: 'widget-debugger',
      i18nKey: 'route.widget-debugger'
    }
  },
  {
    name: 'workspace',
    path: '/workspace',
    component: 'layout.base$view.workspace',
    meta: {
      title: 'workspace',
      i18nKey: 'route.workspace',
      hideInMenu: true
    }
  }
];
